In [1]:
import numpy as np

In [22]:
def normalize(v):
    return v / v.sum()

def transition(x_t):
    # return P(X_t+1|x_t)
    if x_t:
        return np.array([2./3, 1./3])
    else:
        return np.array([0.5, 0.5])
    
def sensor(x_t):
    # return P(E_t|x_t)
    if x_t:
        return np.array([0.8, 0.2])
    else:
        return np.array([0.5, 0.5])

In [23]:
transition(1), transition(0)

(array([ 0.66666667,  0.33333333]), array([ 0.5,  0.5]))

In [24]:
sensor(1), sensor(0)

(array([ 0.8,  0.2]), array([ 0.5,  0.5]))

In [25]:
def forward(e_t1, f):
    p_e_t1 = np.array([0., 0])
    p_e_t1[0] += sensor(1)[0 if e_t1 else 1]
    p_e_t1[1] += sensor(0)[0 if e_t1 else 1]
    
    s = np.array([0., 0.])
    for x_t in [0, 1]:
        s += transition(x_t) * (f[0] if x_t else f[1])
        
    p = np.multiply(p_e_t1, s)
    return normalize(p)
        
f1 = forward(1, np.array([0.5, 0.5]))
print("f1 =", f1)
f2 = forward(1, f1)
print("f2 =", f2)

f1 = [ 0.69135802  0.30864198]
f2 = [ 0.71896604  0.28103396]


In [26]:
def backward(e_k1, b):
    s = np.array([0., 0.])
    
    for x_k1 in [0, 1]:
        w = sensor(x_k1)[0 if e_k1 else 1] * (b[0] if x_k1 else b[1])
        
        p_x_k1 = np.array([0., 0.])
        p_x_k1[0] += transition(1)[0 if x_k1 else 1]
        p_x_k1[1] += transition(0)[0 if x_k1 else 1]
        
        s += w * p_x_k1
        
    return normalize(s)    

In [27]:
b0 = np.array([1.0, 1.0])
print("b0 =", b0)

b0 = [ 1.  1.]


In [28]:
normalize(np.multiply(f2, b0))

array([ 0.71896604,  0.28103396])

In [29]:
b1 = backward(1, b0)
print("b1 =", b1)

b1 = [ 0.51851852  0.48148148]


In [30]:
normalize(np.multiply(f1, b1))

array([ 0.70694319,  0.29305681])