In [6]:
import numpy as np

In [7]:
def normalize(v):
    return v / v.sum()

In [8]:
T = np.array([[0.7, 0.3], 
              [0.3, 0.7]])
O = {True: np.array([[0.9, 0.0], 
                     [0.0, 0.2]]),
     False: np.array([[0.1, 0.0], 
                      [0.0, 0.8]])}

In [9]:
f0 = np.array([0.5, 0.5]).reshape(-1, 1)
evidences = [True, True, False, True, True]

## Forward pass

In [10]:
f1 = normalize(O[evidences[0]] @ T.T @ f0)
f1

array([[0.81818182],
       [0.18181818]])

In [11]:
f2 = normalize(O[evidences[1]] @ T.T @ f1)
f2

array([[0.88335704],
       [0.11664296]])

In [12]:
f3 = normalize(O[evidences[2]] @ T.T @ f2)
f3

array([[0.19066794],
       [0.80933206]])

In [13]:
f4 = normalize(O[evidences[3]] @ T.T @ f3)
f4

array([[0.730794],
       [0.269206]])

In [14]:
f5 = normalize(O[evidences[4]] @ T.T @ f4)
f5

array([[0.86733889],
       [0.13266111]])

## Backward pass

In [15]:
b5 = np.ones((2, 1))
b5

array([[1.],
       [1.]])

In [16]:
b4 = T @ O[evidences[4]] @ b5
b4

array([[0.69],
       [0.41]])

In [17]:
b3 = T @ O[evidences[3]] @ b4
b3

array([[0.4593],
       [0.2437]])

In [18]:
b2 = T @ O[evidences[2]] @ b3
b2

array([[0.090639],
       [0.150251]])

In [19]:
b1 = T @ O[evidences[1]] @ b2
b1

array([[0.06611763],
       [0.04550767]])

In [20]:
b0 = T @ O[evidences[0]] @ b1
b0

array([[0.04438457],
       [0.02422283]])

## Smoothed estimates

In [21]:
normalize(f0 * b0)

array([[0.64693556],
       [0.35306444]])

In [22]:
normalize(f1 * b1)

array([[0.86733889],
       [0.13266111]])

In [23]:
normalize(f2 * b2)

array([[0.82041905],
       [0.17958095]])

In [24]:
normalize(f3 * b3)

array([[0.30748358],
       [0.69251642]])

In [25]:
normalize(f4 * b4)

array([[0.82041905],
       [0.17958095]])

In [26]:
normalize(f5 * b5)

array([[0.86733889],
       [0.13266111]])

## Stationary distribution

In [30]:
f0 = np.array([0.2, 0.8]).reshape(-1,1)

In [31]:
f = f0
for i in range(10):
    f = T.T @ f
    print(f)
f

[[0.38]
 [0.62]]
[[0.452]
 [0.548]]
[[0.4808]
 [0.5192]]
[[0.49232]
 [0.50768]]
[[0.496928]
 [0.503072]]
[[0.4987712]
 [0.5012288]]
[[0.49950848]
 [0.50049152]]
[[0.49980339]
 [0.50019661]]
[[0.49992136]
 [0.50007864]]
[[0.49996854]
 [0.50003146]]


array([[0.49996854],
       [0.50003146]])

In [32]:
values, vectors = np.linalg.eig(T.T)
values, vectors

(array([1. , 0.4]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [33]:
vectors[:, 0] / vectors[:, 0].sum()

array([0.5, 0.5])