In [1]:
import numpy as np

In [2]:
def normalize(v):
    return v / v.sum()

In [3]:
T = np.array([[0.7, 0.3], 
              [0.3, 0.7]])
O = {True: np.array([[0.9, 0.0], 
                     [0.0, 0.2]]),
     False: np.array([[0.1, 0.0], 
                      [0.0, 0.8]])}

In [4]:
f0 = np.array([0.5, 0.5]).reshape(-1, 1)
evidences = [True, True, False, True, True]

## Forward pass

In [5]:
f1 = normalize(O[evidences[0]] @ T.T @ f0)
f1

array([[ 0.81818182],
       [ 0.18181818]])

In [6]:
f2 = normalize(O[evidences[1]] @ T.T @ f1)
f2

array([[ 0.88335704],
       [ 0.11664296]])

In [7]:
f3 = normalize(O[evidences[2]] @ T.T @ f2)
f3

array([[ 0.19066794],
       [ 0.80933206]])

In [8]:
f4 = normalize(O[evidences[3]] @ T.T @ f3)
f4

array([[ 0.730794],
       [ 0.269206]])

In [9]:
f5 = normalize(O[evidences[4]] @ T.T @ f4)
f5

array([[ 0.86733889],
       [ 0.13266111]])

## Backward pass

In [10]:
b5 = np.ones((2, 1))
b5

array([[ 1.],
       [ 1.]])

In [11]:
b4 = normalize(T @ O[evidences[4]] @ b5)
b4

array([[ 0.62727273],
       [ 0.37272727]])

In [12]:
b3 = normalize(T @ O[evidences[3]] @ b4)
b3

array([[ 0.65334282],
       [ 0.34665718]])

In [13]:
b2 = normalize(T @ O[evidences[2]] @ b3)
b2

array([[ 0.37626718],
       [ 0.62373282]])

In [14]:
b1 = normalize(T @ O[evidences[1]] @ b2)
b1

array([[ 0.5923176],
       [ 0.4076824]])

In [15]:
b0 = normalize(T @ O[evidences[0]] @ b1)
b0

array([[ 0.64693556],
       [ 0.35306444]])

## Smoothed estimates

In [16]:
normalize(f0 * b0)

array([[ 0.64693556],
       [ 0.35306444]])

In [17]:
normalize(f1 * b1)

array([[ 0.86733889],
       [ 0.13266111]])

In [18]:
normalize(f2 * b2)

array([[ 0.82041905],
       [ 0.17958095]])

In [19]:
normalize(f3 * b3)

array([[ 0.30748358],
       [ 0.69251642]])

In [20]:
normalize(f4 * b4)

array([[ 0.82041905],
       [ 0.17958095]])

In [21]:
normalize(f5 * b5)

array([[ 0.86733889],
       [ 0.13266111]])